const data= [
  
  {
    id: 1,
    title: "Heel top green",
    price: 599.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405528/ecommerce/download_ewfgzq.jpg",
    category: "women",
    detail:"Gold & Grey",
  },
  {
    id: 2,
    title: "Heel top blue",
    price: 799.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405494/ecommerce/4-fotwear-luxury-shoes-photographer-catalog-bologna_ltifid.jpg",
    category: "women",
    detail:"Gold & Grey",
  },
  {
    id: 3,
    title: "Heel top Grey",
    price: 199.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405509/ecommerce/download_enlwfu.jpg",
    category: "women",
    detail:"Gold & Grey",
  },
  {
    id: 4,
    title: "Perfect Bag",
    price: 799.99,
    img: "../files/xproduct_2.png.pagespeed.ic.xZ0lu64cc1.png",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 5,
    title: "Perfect Book",
    price: 799.99,
    img: "../files/xproduct_8.png.pagespeed.ic.rOL_qj1ADY.png",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 6,
    title: "Perfect Glass",
    price: 799.99,
    img: "../files/xproduct_6.png.pagespeed.ic.-wZZ65ycl2.png",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 7,
    title: "Perfect Capucine",
    price: 799.99,
    img: "../files/xproduct_1.png.pagespeed.ic.cjHWppIIdF.png",
    category: "men",
  },
  {
    id: 8,
    title: "Baby gorgeous",
    price: 299.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405655/ecommerce/download_e3jhnp.jpg",
    category: "baby",
    detail:"Gold & Grey",
  },
  {
    id: 9,
    title: "Men Basketball Irvin",
    price: 799.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405728/ecommerce/download_pjn4gb.jpg",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 10,
    title: "Gentle Awesome",
    price: 799.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405601/ecommerce/images_khcehe.jpg",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 11,
    title: "Perfect Mocasines",
    price: 799.99,
    img:"https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 12,
    title: "Perfect Basket",
    price: 799.99,
    img:" https://images.pexels.com/photos/13565023/pexels-photo-13565023.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 13,
    title: "Great Gentle Black",
    price: 799.99,
    // img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405628/ecommerce/images_cyaohs.jpg",
    img:"http://cdn.shopify.com/s/files/1/0086/8981/1516/products/ypsons-richelieu-homme-san-cuir-noir-semelle-cuir-vue-de-biais.jpg?v=1616698127",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 14,
    title: "Perfect Gentle",
    price: 799.99,
    // img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405575/ecommerce/download_rsv5xd.jpg",
    img:"https://images.pexels.com/photos/19090/pexels-photo.jpg?cs=srgb&dl=pexels-web-donut-19090.jpg&fm=jpg",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 15,
    title: "Daisy Baby",
    price: 799.99,
    img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405684/ecommerce/download_cbfill.jpg",
    category: "baby",
    detail:"Gold & Grey",
  },
  {
    id: 16,
    title: "Great Gentle Coimbra",
    price: 799.99,
    img:"https://www.costume-prive-paris.com/wp-content/uploads/2021/04/clint-coimbra-wingtip-brogue-8035.jpg",
    category: "men",
    detail:"Gold & Grey",
  },
  {
    id: 17,
    title: "Daisy Mocasine",
    price: 799.99,
    // img: "https://res.cloudinary.com/dh9p4f5xs/image/upload/v1665405684/ecommerce/download_cbfill.jpg",
    img:"https://www.hendz.co/wp-content/uploads/2018/07/mocasines-formales-mate-para-hombres.jpg",
    category: "baby",
    detail:"Gold & Grey",
  },
  
];

export default data;